Yasir/job card
Mycro-HQ/bettercareer-fe pull request #4
Opened 2024-03-04 20:48 UTC by YasirGaji

2024-03-05 18:57 UTC, adenekan41 commented on .gitignore
> +.history
What's this for ?

2024-03-05 18:58 UTC, adenekan41 commented on .hintrc
> +{
Hmmm, whats this ??

2024-03-05 18:59 UTC, adenekan41 commented on public/images/jobs/index.ts
> +import CompanyLogo from './Company Logo.png'
Nope, we already have svgr for this so you can simply do 

<img /images/jobs/company_logo.png />

Also never not accentuate your file name without special chars 

```js
//e.g 

// Compay Logo.png

becomes 
// company_logo.png
or 
// company-logo.png

```

2024-03-05 19:00 UTC, adenekan41 commented on src/components/seo/index.ts
> +export * from './jobcard/JobCard'
Christ ??

2024-03-05 19:01 UTC, adenekan41 commented on src/components/seo/jobcard/JobCard.tsx
> +import React from 'react';
What is job card looking for in seo/jobcard ?? 

this is a private / constrainted component so it should easily live inside of 

dashboard/views/homes > a new folder called components

2024-03-05 19:01 UTC, adenekan41 commented on src/components/seo/jobcard/JobCard.tsx
> +import { CompanyLogo } from '../../../../public/images/jobs';
Please delete

2024-03-05 19:01 UTC, adenekan41 commented on src/components/seo/jobcard/JobCard.tsx
> +          <button className={styles.save}>Save</button>
Please use the private `CallToAction` component

2024-03-05 19:02 UTC, adenekan41 commented on src/components/seo/jobcard/JobCard.tsx
> +    <div className={styles.jobCard}>
No camel case. 

styles.jobCard should be styles.JobCard 

looks a lot elegant that way

2024-03-05 19:03 UTC, adenekan41 commented on src/components/seo/jobcard/jobcard.module.scss
> +  }
Nope ?? never do this. ever 

```suggestion
width: 100%; 
```

does the trick

2024-03-05 19:04 UTC, adenekan41 commented on src/components/seo/jobcard/jobcard.module.scss
> +  padding-bottom: 1.7rem;
please lets refrain `rem` and i hate it let's use px and use the rem wrapper i have in place so 

```scss
gap: rem(14px)
```

2024-03-05 19:04 UTC, adenekan41 commented on src/components/seo/jobcard/jobcard.module.scss
> +    }
WHy ???

2024-03-05 19:04 UTC, adenekan41 commented on src/components/seo/jobcard/jobcard.module.scss
> +      }
Whats with the sparring `media` query ??

2024-03-05 19:05 UTC, adenekan41 commented on src/components/seo/jobcard/jobcard.module.scss
> +        }
Nope never hard code `font-size` we have a declarative direction

2024-03-05 19:06 UTC, adenekan41 commented on src/components/seo/jobcard/jobcard.module.scss
> +        border-radius: 9999px; /* Rounded to full for circular shape */
50px is just about fine here, but they won't be any need for this cus we are using the actual buttons i created

2024-03-05 19:07 UTC, adenekan41 commented on src/features/dashboard/views/home/home.tsx
> +			<JobCard />
Lets just have a structural data for the job cards and map it e.g 

```tsx
const JOBS = [
	{
		...blah blah
	}
]

and you map below 
```

2024-03-05 19:17 UTC, adenekan41 requested changes
Let's fix these

2024-03-06 21:34 UTC, YasirGaji commented on .gitignore
> +.history
Fixeed

2024-03-06 21:34 UTC, YasirGaji commented on .hintrc
> +{
fixed

2024-03-06 21:34 UTC, YasirGaji commented on public/images/jobs/index.ts
> +import CompanyLogo from './Company Logo.png'
Corrected

2024-03-06 21:34 UTC, YasirGaji commented on src/components/seo/index.ts
> +export * from './jobcard/JobCard'
Fixed

2024-03-06 21:34 UTC, YasirGaji commented on src/components/seo/jobcard/JobCard.tsx
> +import React from 'react';
corrected

2024-03-06 21:34 UTC, YasirGaji commented on src/components/seo/jobcard/JobCard.tsx
> +import { CompanyLogo } from '../../../../public/images/jobs';
Done

2024-03-06 21:34 UTC, YasirGaji commented on src/components/seo/jobcard/JobCard.tsx
> +          <button className={styles.save}>Save</button>
done

2024-03-06 21:34 UTC, YasirGaji commented on src/components/seo/jobcard/JobCard.tsx
> +    <div className={styles.jobCard}>
Done

2024-03-06 21:34 UTC, YasirGaji commented on src/components/seo/jobcard/jobcard.module.scss
> +  }
Done

2024-03-06 21:34 UTC, YasirGaji commented on src/components/seo/jobcard/jobcard.module.scss
> +  padding-bottom: 1.7rem;
fixed

2024-03-06 21:34 UTC, YasirGaji commented on src/components/seo/jobcard/jobcard.module.scss
> +      }
corrected

2024-03-06 21:35 UTC, YasirGaji commented on src/components/seo/jobcard/jobcard.module.scss
> +        }
Corrected

2024-03-06 21:35 UTC, YasirGaji commented on src/components/seo/jobcard/jobcard.module.scss
> +        border-radius: 9999px; /* Rounded to full for circular shape */
Corrected

2024-03-06 21:35 UTC, YasirGaji commented on src/features/dashboard/views/home/home.tsx
> +			<JobCard />
Done

2024-03-07 06:31 UTC, adenekan41 commented on src/features/dashboard/views/home/component/jobcard/jobcard.module.scss
> +      width: 177px;
Why ?

2024-03-07 06:31 UTC, adenekan41 commented on src/features/dashboard/views/home/component/jobcard/jobcard.module.scss
> +        width: 79px;
Why ?

2024-03-07 06:31 UTC, adenekan41 commented on src/features/dashboard/views/home/component/jobcard/jobcard.module.scss
> +        height: 42px;
Why ?

2024-03-07 06:32 UTC, adenekan41 commented on src/features/dashboard/views/home/component/jobcard/jobcard.module.scss
> +        width: 90px;
Why ?

these things are already set by the directive component

2024-03-07 06:32 UTC, adenekan41 commented on src/features/dashboard/views/home/component/jobcard/jobcard.module.scss
> +        height: 42px;
Why ?

2024-03-07 06:33 UTC, adenekan41 commented on src/features/dashboard/views/home/component/jobcard/jobcard.module.scss
> +    width: 283px;
Why ?

always set dynamic w x h with properties like "padding"

2024-03-07 06:33 UTC, adenekan41 commented on src/features/dashboard/views/home/component/jobcard/jobcard.module.scss
> +      width: 87px;
Why ?

Stop setting hard width and height

2024-03-07 06:34 UTC, adenekan41 commented on .hintrc
> +{
Please remove this file. and remove it from your cache

2024-03-07 06:34 UTC, adenekan41 commented on .gitignore
> +.history
i still see `.history`

2024-03-07 06:34 UTC, adenekan41 commented on src/features/dashboard/views/home/component/jobcard/jobcard.module.scss
> +      height: 32px;
Why ?

2024-03-07 06:35 UTC, adenekan41 commented on src/features/dashboard/views/home/component/jobcard/jobcard.module.scss
> +        width: 90px;
you don't need to set these

2024-05-07 02:15 UTC, closed without merging